apiVersion: network.vcd.upbound.io/v1beta1
kind: Direct
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/direct
  labels:
    testing.upbound.io/example-name: net
  name: net
spec:
  forProvider:
    externalNetworkSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    org: my-org
    vdc: my-vdc

---

