apiVersion: network.vcd.upbound.io/v1alpha1
kind: Direct
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/direct
  labels:
    testing.upbound.io/example-name: net
  name: net
spec:
  forProvider:
    externalNetwork: my-ext-net
    org: my-org
    vdc: my-vdc

---

