apiVersion: network.vcd.upbound.io/v1beta1
kind: RoutedV2
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/routedv2
  labels:
    testing.upbound.io/example-name: nsxt-backed
  name: nsxt-backed
spec:
  forProvider:
    description: My routed Org VDC network backed by NSX-T
    edgeGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcd_nsxt_edgegateway
    gateway: 1.1.1.1
    org: my-org
    prefixLength: 24
    staticIpPool:
    - endAddress: 1.1.1.20
      startAddress: 1.1.1.10
    - endAddress: 1.1.1.103
      startAddress: 1.1.1.100

---

