/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EdgeGatewayObservation struct {

	// IP address of edge gateway used for default network
	// IP address of edge gateway interface which is used as default.
	DefaultExternalNetworkIP *string `json:"defaultExternalNetworkIp,omitempty" tf:"default_external_network_ip,omitempty"`

	// A list of IP addresses assigned to edge gateway interfaces
	// connected to external networks.
	// List of IP addresses set on edge gateway external network interfaces
	ExternalNetworkIps []*string `json:"externalNetworkIps,omitempty" tf:"external_network_ips,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type EdgeGatewayParameters struct {

	// Configuration of the vShield edge VM for this gateway. One of: compact, full ("Large"), x-large, full4 ("Quad Large").
	// Configuration of the vShield edge VM for this gateway. One of: compact, full ("Large"), full4 ("Quad Large"), x-large
	// +kubebuilder:validation:Required
	Configuration *string `json:"configuration" tf:"configuration,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// If advanced networking enabled, also enable distributed
	// routing. Default is false.
	// Enable distributed routing
	// +kubebuilder:validation:Optional
	DistributedRouting *bool `json:"distributedRouting,omitempty" tf:"distributed_routing,omitempty"`

	// One or more blocks defining external networks, their
	// subnets, IP addresses and  IP pool suballocation attached to edge gateway interfaces. Details are
	// in external network block below.
	// One or more blocks with external network information to be attached to this gateway's interface
	// +kubebuilder:validation:Required
	ExternalNetwork []ExternalNetworkParameters `json:"externalNetwork" tf:"external_network,omitempty"`

	// When FIPS mode is enabled, any secure communication to or from
	// the NSX Edge uses cryptographic algorithms or protocols that are allowed by United States Federal
	// Information Processing Standards (FIPS). FIPS mode turns on the cipher suites that comply with
	// FIPS. Default is false. Note: to use FIPS mode it must be enabled in vCD system settings.
	// Enable FIPS mode. FIPS mode turns on the cipher suites that comply with FIPS. (False by default)
	// +kubebuilder:validation:Optional
	FipsModeEnabled *bool `json:"fipsModeEnabled,omitempty" tf:"fips_mode_enabled,omitempty"`

	// Default firewall rule (last in the processing order) action.
	// One of accept or deny. Default deny.
	// 'accept' or 'deny'. Default 'deny'
	// +kubebuilder:validation:Optional
	FwDefaultRuleAction *string `json:"fwDefaultRuleAction,omitempty" tf:"fw_default_rule_action,omitempty"`

	// Enable default firewall rule (last in the processing
	// order) logging. Default false.
	// Enable logging for default rule. Default 'false'
	// +kubebuilder:validation:Optional
	FwDefaultRuleLoggingEnabled *bool `json:"fwDefaultRuleLoggingEnabled,omitempty" tf:"fw_default_rule_logging_enabled,omitempty"`

	// Enable firewall. Default true. Note: Disabling Firewall will also
	// disable NAT and other NAT dependent features like Load Balancer.
	// Enable firewall. Default 'true'
	// +kubebuilder:validation:Optional
	FwEnabled *bool `json:"fwEnabled,omitempty" tf:"fw_enabled,omitempty"`

	// Enable high availability on this edge gateway. Default is false.
	// Enable high availability on this edge gateway
	// +kubebuilder:validation:Optional
	HaEnabled *bool `json:"haEnabled,omitempty" tf:"ha_enabled,omitempty"`

	// Enable to configure the load balancer to use the faster L4
	// engine rather than L7 engine. The L4 TCP VIP is processed before the edge gateway firewall so no
	// allow firewall rule is required. Default is false. Note: L7 VIPs for HTTP and HTTPS are
	// processed after the firewall, so when Acceleration Enabled is not selected, an edge gateway firewall
	// rule must exist to allow access to the L7 VIP for those protocols. When Acceleration Enabled is
	// selected and the server pool is in non-transparent mode, an SNAT rule is added, so you must ensure
	// that the firewall is enabled on the edge gateway.
	// Enable load balancer acceleration. (Disabled by default)
	// +kubebuilder:validation:Optional
	LBAccelerationEnabled *bool `json:"lbAccelerationEnabled,omitempty" tf:"lb_acceleration_enabled,omitempty"`

	// Enable load balancing. Default is false.
	// Enable load balancing. (Disabled by default)
	// +kubebuilder:validation:Optional
	LBEnabled *bool `json:"lbEnabled,omitempty" tf:"lb_enabled,omitempty"`

	// Enables the edge gateway load balancer to collect traffic logs.
	// Default is false.
	// Enable load balancer logging. (Disabled by default)
	// +kubebuilder:validation:Optional
	LBLoggingEnabled *bool `json:"lbLoggingEnabled,omitempty" tf:"lb_logging_enabled,omitempty"`

	// Choose the severity of events to be logged. One of emergency,
	// alert, critical, error, warning, notice, info, debug
	// Log level. One of 'emergency', 'alert', 'critical', 'error', 'warning', 'notice', 'info', 'debug'. ('info' by default)
	// +kubebuilder:validation:Optional
	LBLoglevel *string `json:"lbLoglevel,omitempty" tf:"lb_loglevel,omitempty"`

	// The name of organization to which the VDC belongs. Optional if defined at provider level.
	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// When default route is set, it will be used for
	// gateways' default routing and DNS forwarding. Default is false.
	// If true, default gateway will be used for the edge gateways' default routing and DNS forwarding.(False by default)
	// +kubebuilder:validation:Optional
	UseDefaultRouteForDNSRelay *bool `json:"useDefaultRouteForDnsRelay,omitempty" tf:"use_default_route_for_dns_relay,omitempty"`

	// The name of VDC that owns the edge gateway. Optional if defined at provider level.
	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type ExternalNetworkObservation struct {
}

type ExternalNetworkParameters struct {

	// True if rate limiting should be applied on this interface.
	// Default is false.
	// Enable rate limiting
	// +kubebuilder:validation:Optional
	EnableRateLimit *bool `json:"enableRateLimit,omitempty" tf:"enable_rate_limit,omitempty"`

	// Incoming rate limit in Mbps.
	// Incoming rate limit (Mbps)
	// +kubebuilder:validation:Optional
	IncomingRateLimit *float64 `json:"incomingRateLimit,omitempty" tf:"incoming_rate_limit,omitempty"`

	// A unique name for the edge gateway.
	// External network name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Outgoing rate limit in Mbps.
	// Outgoing rate limit (Mbps)
	// +kubebuilder:validation:Optional
	OutgoingRateLimit *float64 `json:"outgoingRateLimit,omitempty" tf:"outgoing_rate_limit,omitempty"`

	// One or more blocks of External Network Subnet.
	// +kubebuilder:validation:Optional
	Subnet []SubnetParameters `json:"subnet,omitempty" tf:"subnet,omitempty"`
}

type SuballocatePoolObservation struct {
}

type SuballocatePoolParameters struct {

	// End IP address of a range
	// +kubebuilder:validation:Required
	EndAddress *string `json:"endAddress" tf:"end_address,omitempty"`

	// Start IP address of a range
	// +kubebuilder:validation:Required
	StartAddress *string `json:"startAddress" tf:"start_address,omitempty"`
}

type SubnetObservation struct {
}

type SubnetParameters struct {

	// Gateway for a subnet in external network
	// Gateway address for a subnet
	// +kubebuilder:validation:Required
	Gateway *string `json:"gateway" tf:"gateway,omitempty"`

	// IP address to assign to edge gateway interface (will be auto-assigned if
	// unspecified)
	// IP address on the edge gateway - will be auto-assigned if not defined
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Netmask of a subnet in external network
	// Netmask address for a subnet
	// +kubebuilder:validation:Required
	Netmask *string `json:"netmask" tf:"netmask,omitempty"`

	// One or more blocks of ip
	// ranges in the subnet to be sub-allocated
	// Define zero or more blocks to sub-allocate pools on the edge gateway
	// +kubebuilder:validation:Optional
	SuballocatePool []SuballocatePoolParameters `json:"suballocatePool,omitempty" tf:"suballocate_pool,omitempty"`

	// Should this network be used as default gateway on edge
	// gateway. Default is false.
	// Defines if this subnet should be used as default gateway for edge
	// +kubebuilder:validation:Optional
	UseForDefaultRoute *bool `json:"useForDefaultRoute,omitempty" tf:"use_for_default_route,omitempty"`
}

// EdgeGatewaySpec defines the desired state of EdgeGateway
type EdgeGatewaySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EdgeGatewayParameters `json:"forProvider"`
}

// EdgeGatewayStatus defines the observed state of EdgeGateway.
type EdgeGatewayStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EdgeGatewayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// EdgeGateway is the Schema for the EdgeGateways API. Provides a VMware Cloud Director edge gateway. This can be used to create and delete edge gateways connected to one or more external networks.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type EdgeGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              EdgeGatewaySpec   `json:"spec"`
	Status            EdgeGatewayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EdgeGatewayList contains a list of EdgeGateways
type EdgeGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EdgeGateway `json:"items"`
}

// Repository type metadata.
var (
	EdgeGateway_Kind             = "EdgeGateway"
	EdgeGateway_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EdgeGateway_Kind}.String()
	EdgeGateway_KindAPIVersion   = EdgeGateway_Kind + "." + CRDGroupVersion.String()
	EdgeGateway_GroupVersionKind = CRDGroupVersion.WithKind(EdgeGateway_Kind)
)

func init() {
	SchemeBuilder.Register(&EdgeGateway{}, &EdgeGatewayList{})
}
