//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControl) DeepCopyInto(out *AccessControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControl.
func (in *AccessControl) DeepCopy() *AccessControl {
	if in == nil {
		return nil
	}
	out := new(AccessControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlList) DeepCopyInto(out *AccessControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlList.
func (in *AccessControlList) DeepCopy() *AccessControlList {
	if in == nil {
		return nil
	}
	out := new(AccessControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlObservation) DeepCopyInto(out *AccessControlObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlObservation.
func (in *AccessControlObservation) DeepCopy() *AccessControlObservation {
	if in == nil {
		return nil
	}
	out := new(AccessControlObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlParameters) DeepCopyInto(out *AccessControlParameters) {
	*out = *in
	if in.CatalogID != nil {
		in, out := &in.CatalogID, &out.CatalogID
		*out = new(string)
		**out = **in
	}
	if in.CatalogIDRef != nil {
		in, out := &in.CatalogIDRef, &out.CatalogIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogIDSelector != nil {
		in, out := &in.CatalogIDSelector, &out.CatalogIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.EveryoneAccessLevel != nil {
		in, out := &in.EveryoneAccessLevel, &out.EveryoneAccessLevel
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.SharedWith != nil {
		in, out := &in.SharedWith, &out.SharedWith
		*out = make([]SharedWithParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SharedWithEveryone != nil {
		in, out := &in.SharedWithEveryone, &out.SharedWithEveryone
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlParameters.
func (in *AccessControlParameters) DeepCopy() *AccessControlParameters {
	if in == nil {
		return nil
	}
	out := new(AccessControlParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlSpec) DeepCopyInto(out *AccessControlSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlSpec.
func (in *AccessControlSpec) DeepCopy() *AccessControlSpec {
	if in == nil {
		return nil
	}
	out := new(AccessControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlStatus) DeepCopyInto(out *AccessControlStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlStatus.
func (in *AccessControlStatus) DeepCopy() *AccessControlStatus {
	if in == nil {
		return nil
	}
	out := new(AccessControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Catalog) DeepCopyInto(out *Catalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Catalog.
func (in *Catalog) DeepCopy() *Catalog {
	if in == nil {
		return nil
	}
	out := new(Catalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Catalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogList) DeepCopyInto(out *CatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Catalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogList.
func (in *CatalogList) DeepCopy() *CatalogList {
	if in == nil {
		return nil
	}
	out := new(CatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogObservation) DeepCopyInto(out *CatalogObservation) {
	*out = *in
	if in.CatalogVersion != nil {
		in, out := &in.CatalogVersion, &out.CatalogVersion
		*out = new(float64)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.Href != nil {
		in, out := &in.Href, &out.Href
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsLocal != nil {
		in, out := &in.IsLocal, &out.IsLocal
		*out = new(bool)
		**out = **in
	}
	if in.IsPublished != nil {
		in, out := &in.IsPublished, &out.IsPublished
		*out = new(bool)
		**out = **in
	}
	if in.IsShared != nil {
		in, out := &in.IsShared, &out.IsShared
		*out = new(bool)
		**out = **in
	}
	if in.MediaItemList != nil {
		in, out := &in.MediaItemList, &out.MediaItemList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.NumberOfMedia != nil {
		in, out := &in.NumberOfMedia, &out.NumberOfMedia
		*out = new(float64)
		**out = **in
	}
	if in.NumberOfVappTemplates != nil {
		in, out := &in.NumberOfVappTemplates, &out.NumberOfVappTemplates
		*out = new(float64)
		**out = **in
	}
	if in.OwnerName != nil {
		in, out := &in.OwnerName, &out.OwnerName
		*out = new(string)
		**out = **in
	}
	if in.PublishSubscriptionType != nil {
		in, out := &in.PublishSubscriptionType, &out.PublishSubscriptionType
		*out = new(string)
		**out = **in
	}
	if in.PublishSubscriptionURL != nil {
		in, out := &in.PublishSubscriptionURL, &out.PublishSubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.VappTemplateList != nil {
		in, out := &in.VappTemplateList, &out.VappTemplateList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogObservation.
func (in *CatalogObservation) DeepCopy() *CatalogObservation {
	if in == nil {
		return nil
	}
	out := new(CatalogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogParameters) DeepCopyInto(out *CatalogParameters) {
	*out = *in
	if in.CacheEnabled != nil {
		in, out := &in.CacheEnabled, &out.CacheEnabled
		*out = new(bool)
		**out = **in
	}
	if in.DeleteForce != nil {
		in, out := &in.DeleteForce, &out.DeleteForce
		*out = new(bool)
		**out = **in
	}
	if in.DeleteRecursive != nil {
		in, out := &in.DeleteRecursive, &out.DeleteRecursive
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]MetadataEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.PreserveIdentityInformation != nil {
		in, out := &in.PreserveIdentityInformation, &out.PreserveIdentityInformation
		*out = new(bool)
		**out = **in
	}
	if in.PublishEnabled != nil {
		in, out := &in.PublishEnabled, &out.PublishEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StorageProfileID != nil {
		in, out := &in.StorageProfileID, &out.StorageProfileID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogParameters.
func (in *CatalogParameters) DeepCopy() *CatalogParameters {
	if in == nil {
		return nil
	}
	out := new(CatalogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogSpec) DeepCopyInto(out *CatalogSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogSpec.
func (in *CatalogSpec) DeepCopy() *CatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogStatus) DeepCopyInto(out *CatalogStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogStatus.
func (in *CatalogStatus) DeepCopy() *CatalogStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Item) DeepCopyInto(out *Item) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Item.
func (in *Item) DeepCopy() *Item {
	if in == nil {
		return nil
	}
	out := new(Item)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Item) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemList) DeepCopyInto(out *ItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Item, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemList.
func (in *ItemList) DeepCopy() *ItemList {
	if in == nil {
		return nil
	}
	out := new(ItemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemMetadataEntryObservation) DeepCopyInto(out *ItemMetadataEntryObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemMetadataEntryObservation.
func (in *ItemMetadataEntryObservation) DeepCopy() *ItemMetadataEntryObservation {
	if in == nil {
		return nil
	}
	out := new(ItemMetadataEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemMetadataEntryParameters) DeepCopyInto(out *ItemMetadataEntryParameters) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemMetadataEntryParameters.
func (in *ItemMetadataEntryParameters) DeepCopy() *ItemMetadataEntryParameters {
	if in == nil {
		return nil
	}
	out := new(ItemMetadataEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemObservation) DeepCopyInto(out *ItemObservation) {
	*out = *in
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemObservation.
func (in *ItemObservation) DeepCopy() *ItemObservation {
	if in == nil {
		return nil
	}
	out := new(ItemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemParameters) DeepCopyInto(out *ItemParameters) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.CatalogItemMetadata != nil {
		in, out := &in.CatalogItemMetadata, &out.CatalogItemMetadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]ItemMetadataEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OvaPath != nil {
		in, out := &in.OvaPath, &out.OvaPath
		*out = new(string)
		**out = **in
	}
	if in.OvfURL != nil {
		in, out := &in.OvfURL, &out.OvfURL
		*out = new(string)
		**out = **in
	}
	if in.ShowUploadProgress != nil {
		in, out := &in.ShowUploadProgress, &out.ShowUploadProgress
		*out = new(bool)
		**out = **in
	}
	if in.UploadPieceSize != nil {
		in, out := &in.UploadPieceSize, &out.UploadPieceSize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemParameters.
func (in *ItemParameters) DeepCopy() *ItemParameters {
	if in == nil {
		return nil
	}
	out := new(ItemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemSpec) DeepCopyInto(out *ItemSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemSpec.
func (in *ItemSpec) DeepCopy() *ItemSpec {
	if in == nil {
		return nil
	}
	out := new(ItemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemStatus) DeepCopyInto(out *ItemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemStatus.
func (in *ItemStatus) DeepCopy() *ItemStatus {
	if in == nil {
		return nil
	}
	out := new(ItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Media) DeepCopyInto(out *Media) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Media.
func (in *Media) DeepCopy() *Media {
	if in == nil {
		return nil
	}
	out := new(Media)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Media) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaList) DeepCopyInto(out *MediaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Media, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaList.
func (in *MediaList) DeepCopy() *MediaList {
	if in == nil {
		return nil
	}
	out := new(MediaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MediaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaMetadataEntryObservation) DeepCopyInto(out *MediaMetadataEntryObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaMetadataEntryObservation.
func (in *MediaMetadataEntryObservation) DeepCopy() *MediaMetadataEntryObservation {
	if in == nil {
		return nil
	}
	out := new(MediaMetadataEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaMetadataEntryParameters) DeepCopyInto(out *MediaMetadataEntryParameters) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaMetadataEntryParameters.
func (in *MediaMetadataEntryParameters) DeepCopy() *MediaMetadataEntryParameters {
	if in == nil {
		return nil
	}
	out := new(MediaMetadataEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaObservation) DeepCopyInto(out *MediaObservation) {
	*out = *in
	if in.CreationDate != nil {
		in, out := &in.CreationDate, &out.CreationDate
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsIso != nil {
		in, out := &in.IsIso, &out.IsIso
		*out = new(bool)
		**out = **in
	}
	if in.IsPublished != nil {
		in, out := &in.IsPublished, &out.IsPublished
		*out = new(bool)
		**out = **in
	}
	if in.OwnerName != nil {
		in, out := &in.OwnerName, &out.OwnerName
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(float64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.StorageProfileName != nil {
		in, out := &in.StorageProfileName, &out.StorageProfileName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaObservation.
func (in *MediaObservation) DeepCopy() *MediaObservation {
	if in == nil {
		return nil
	}
	out := new(MediaObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaParameters) DeepCopyInto(out *MediaParameters) {
	*out = *in
	if in.Catalog != nil {
		in, out := &in.Catalog, &out.Catalog
		*out = new(string)
		**out = **in
	}
	if in.CatalogRef != nil {
		in, out := &in.CatalogRef, &out.CatalogRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogSelector != nil {
		in, out := &in.CatalogSelector, &out.CatalogSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.MediaPath != nil {
		in, out := &in.MediaPath, &out.MediaPath
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]MediaMetadataEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.UploadPieceSize != nil {
		in, out := &in.UploadPieceSize, &out.UploadPieceSize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaParameters.
func (in *MediaParameters) DeepCopy() *MediaParameters {
	if in == nil {
		return nil
	}
	out := new(MediaParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaSpec) DeepCopyInto(out *MediaSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaSpec.
func (in *MediaSpec) DeepCopy() *MediaSpec {
	if in == nil {
		return nil
	}
	out := new(MediaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MediaStatus) DeepCopyInto(out *MediaStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MediaStatus.
func (in *MediaStatus) DeepCopy() *MediaStatus {
	if in == nil {
		return nil
	}
	out := new(MediaStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataEntryObservation) DeepCopyInto(out *MetadataEntryObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataEntryObservation.
func (in *MetadataEntryObservation) DeepCopy() *MetadataEntryObservation {
	if in == nil {
		return nil
	}
	out := new(MetadataEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetadataEntryParameters) DeepCopyInto(out *MetadataEntryParameters) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetadataEntryParameters.
func (in *MetadataEntryParameters) DeepCopy() *MetadataEntryParameters {
	if in == nil {
		return nil
	}
	out := new(MetadataEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedWithObservation) DeepCopyInto(out *SharedWithObservation) {
	*out = *in
	if in.SubjectName != nil {
		in, out := &in.SubjectName, &out.SubjectName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedWithObservation.
func (in *SharedWithObservation) DeepCopy() *SharedWithObservation {
	if in == nil {
		return nil
	}
	out := new(SharedWithObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedWithParameters) DeepCopyInto(out *SharedWithParameters) {
	*out = *in
	if in.AccessLevel != nil {
		in, out := &in.AccessLevel, &out.AccessLevel
		*out = new(string)
		**out = **in
	}
	if in.GroupID != nil {
		in, out := &in.GroupID, &out.GroupID
		*out = new(string)
		**out = **in
	}
	if in.OrgID != nil {
		in, out := &in.OrgID, &out.OrgID
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedWithParameters.
func (in *SharedWithParameters) DeepCopy() *SharedWithParameters {
	if in == nil {
		return nil
	}
	out := new(SharedWithParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalog) DeepCopyInto(out *SubscribedCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalog.
func (in *SubscribedCatalog) DeepCopy() *SubscribedCatalog {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscribedCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalogList) DeepCopyInto(out *SubscribedCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubscribedCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalogList.
func (in *SubscribedCatalogList) DeepCopy() *SubscribedCatalogList {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscribedCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalogObservation) DeepCopyInto(out *SubscribedCatalogObservation) {
	*out = *in
	if in.CatalogVersion != nil {
		in, out := &in.CatalogVersion, &out.CatalogVersion
		*out = new(float64)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.FailedTasks != nil {
		in, out := &in.FailedTasks, &out.FailedTasks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Href != nil {
		in, out := &in.Href, &out.Href
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsLocal != nil {
		in, out := &in.IsLocal, &out.IsLocal
		*out = new(bool)
		**out = **in
	}
	if in.IsPublished != nil {
		in, out := &in.IsPublished, &out.IsPublished
		*out = new(bool)
		**out = **in
	}
	if in.IsShared != nil {
		in, out := &in.IsShared, &out.IsShared
		*out = new(bool)
		**out = **in
	}
	if in.MediaItemList != nil {
		in, out := &in.MediaItemList, &out.MediaItemList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NumberOfMedia != nil {
		in, out := &in.NumberOfMedia, &out.NumberOfMedia
		*out = new(float64)
		**out = **in
	}
	if in.NumberOfVappTemplates != nil {
		in, out := &in.NumberOfVappTemplates, &out.NumberOfVappTemplates
		*out = new(float64)
		**out = **in
	}
	if in.OwnerName != nil {
		in, out := &in.OwnerName, &out.OwnerName
		*out = new(string)
		**out = **in
	}
	if in.PublishSubscriptionType != nil {
		in, out := &in.PublishSubscriptionType, &out.PublishSubscriptionType
		*out = new(string)
		**out = **in
	}
	if in.RunningTasks != nil {
		in, out := &in.RunningTasks, &out.RunningTasks
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TasksFileName != nil {
		in, out := &in.TasksFileName, &out.TasksFileName
		*out = new(string)
		**out = **in
	}
	if in.VappTemplateList != nil {
		in, out := &in.VappTemplateList, &out.VappTemplateList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalogObservation.
func (in *SubscribedCatalogObservation) DeepCopy() *SubscribedCatalogObservation {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalogParameters) DeepCopyInto(out *SubscribedCatalogParameters) {
	*out = *in
	if in.CancelFailedTasks != nil {
		in, out := &in.CancelFailedTasks, &out.CancelFailedTasks
		*out = new(bool)
		**out = **in
	}
	if in.DeleteForce != nil {
		in, out := &in.DeleteForce, &out.DeleteForce
		*out = new(bool)
		**out = **in
	}
	if in.DeleteRecursive != nil {
		in, out := &in.DeleteRecursive, &out.DeleteRecursive
		*out = new(bool)
		**out = **in
	}
	if in.MakeLocalCopy != nil {
		in, out := &in.MakeLocalCopy, &out.MakeLocalCopy
		*out = new(bool)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.StorageProfileID != nil {
		in, out := &in.StorageProfileID, &out.StorageProfileID
		*out = new(string)
		**out = **in
	}
	if in.StoreTasks != nil {
		in, out := &in.StoreTasks, &out.StoreTasks
		*out = new(bool)
		**out = **in
	}
	if in.SubscriptionPasswordSecretRef != nil {
		in, out := &in.SubscriptionPasswordSecretRef, &out.SubscriptionPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SubscriptionURL != nil {
		in, out := &in.SubscriptionURL, &out.SubscriptionURL
		*out = new(string)
		**out = **in
	}
	if in.SyncAll != nil {
		in, out := &in.SyncAll, &out.SyncAll
		*out = new(bool)
		**out = **in
	}
	if in.SyncAllMediaItems != nil {
		in, out := &in.SyncAllMediaItems, &out.SyncAllMediaItems
		*out = new(bool)
		**out = **in
	}
	if in.SyncAllVappTemplates != nil {
		in, out := &in.SyncAllVappTemplates, &out.SyncAllVappTemplates
		*out = new(bool)
		**out = **in
	}
	if in.SyncCatalog != nil {
		in, out := &in.SyncCatalog, &out.SyncCatalog
		*out = new(bool)
		**out = **in
	}
	if in.SyncMediaItems != nil {
		in, out := &in.SyncMediaItems, &out.SyncMediaItems
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SyncOnRefresh != nil {
		in, out := &in.SyncOnRefresh, &out.SyncOnRefresh
		*out = new(bool)
		**out = **in
	}
	if in.SyncVappTemplates != nil {
		in, out := &in.SyncVappTemplates, &out.SyncVappTemplates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalogParameters.
func (in *SubscribedCatalogParameters) DeepCopy() *SubscribedCatalogParameters {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalogSpec) DeepCopyInto(out *SubscribedCatalogSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalogSpec.
func (in *SubscribedCatalogSpec) DeepCopy() *SubscribedCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscribedCatalogStatus) DeepCopyInto(out *SubscribedCatalogStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscribedCatalogStatus.
func (in *SubscribedCatalogStatus) DeepCopy() *SubscribedCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(SubscribedCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplate) DeepCopyInto(out *VappTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplate.
func (in *VappTemplate) DeepCopy() *VappTemplate {
	if in == nil {
		return nil
	}
	out := new(VappTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VappTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateList) DeepCopyInto(out *VappTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VappTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateList.
func (in *VappTemplateList) DeepCopy() *VappTemplateList {
	if in == nil {
		return nil
	}
	out := new(VappTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VappTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateMetadataEntryObservation) DeepCopyInto(out *VappTemplateMetadataEntryObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateMetadataEntryObservation.
func (in *VappTemplateMetadataEntryObservation) DeepCopy() *VappTemplateMetadataEntryObservation {
	if in == nil {
		return nil
	}
	out := new(VappTemplateMetadataEntryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateMetadataEntryParameters) DeepCopyInto(out *VappTemplateMetadataEntryParameters) {
	*out = *in
	if in.IsSystem != nil {
		in, out := &in.IsSystem, &out.IsSystem
		*out = new(bool)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UserAccess != nil {
		in, out := &in.UserAccess, &out.UserAccess
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateMetadataEntryParameters.
func (in *VappTemplateMetadataEntryParameters) DeepCopy() *VappTemplateMetadataEntryParameters {
	if in == nil {
		return nil
	}
	out := new(VappTemplateMetadataEntryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateObservation) DeepCopyInto(out *VappTemplateObservation) {
	*out = *in
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.VMNames != nil {
		in, out := &in.VMNames, &out.VMNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VdcID != nil {
		in, out := &in.VdcID, &out.VdcID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateObservation.
func (in *VappTemplateObservation) DeepCopy() *VappTemplateObservation {
	if in == nil {
		return nil
	}
	out := new(VappTemplateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateParameters) DeepCopyInto(out *VappTemplateParameters) {
	*out = *in
	if in.CatalogID != nil {
		in, out := &in.CatalogID, &out.CatalogID
		*out = new(string)
		**out = **in
	}
	if in.CatalogIDRef != nil {
		in, out := &in.CatalogIDRef, &out.CatalogIDRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.CatalogIDSelector != nil {
		in, out := &in.CatalogIDSelector, &out.CatalogIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.MetadataEntry != nil {
		in, out := &in.MetadataEntry, &out.MetadataEntry
		*out = make([]VappTemplateMetadataEntryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Org != nil {
		in, out := &in.Org, &out.Org
		*out = new(string)
		**out = **in
	}
	if in.OvaPath != nil {
		in, out := &in.OvaPath, &out.OvaPath
		*out = new(string)
		**out = **in
	}
	if in.OvfURL != nil {
		in, out := &in.OvfURL, &out.OvfURL
		*out = new(string)
		**out = **in
	}
	if in.UploadPieceSize != nil {
		in, out := &in.UploadPieceSize, &out.UploadPieceSize
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateParameters.
func (in *VappTemplateParameters) DeepCopy() *VappTemplateParameters {
	if in == nil {
		return nil
	}
	out := new(VappTemplateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateSpec) DeepCopyInto(out *VappTemplateSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateSpec.
func (in *VappTemplateSpec) DeepCopy() *VappTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(VappTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VappTemplateStatus) DeepCopyInto(out *VappTemplateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VappTemplateStatus.
func (in *VappTemplateStatus) DeepCopy() *VappTemplateStatus {
	if in == nil {
		return nil
	}
	out := new(VappTemplateStatus)
	in.DeepCopyInto(out)
	return out
}
