apiVersion: nsxt.vcd.upbound.io/v1beta1
kind: EdgeGateway
metadata:
  annotations:
    meta.upbound.io/example-id: nsxt/v1beta1/edgegateway
  labels:
    testing.upbound.io/example-name: nsxt-edge
  name: nsxt-edge
spec:
  forProvider:
    description: Description
    externalNetworkId: ${data.vcd_external_network_v2.nsxt-ext-net.id}
    org: my-org
    ownerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcd_org_vdc
    subnet:
    - allocatedIps:
      - endAddress: 10.150.160.138
        startAddress: 10.150.160.137
      gateway: 10.150.191.253
      prefixLength: "19"
      primaryIp: 10.150.160.137

---

