apiVersion: egw.vcd.upbound.io/v1alpha1
kind: EdgeGateway
metadata:
  annotations:
    meta.upbound.io/example-id: egw/v1alpha1/edgegateway
  labels:
    testing.upbound.io/example-name: egw
  name: egw
spec:
  forProvider:
    configuration: compact
    description: new edge gateway
    externalNetwork:
    - name: my-ext-net1
      subnet:
      - gateway: 192.168.30.49
        ipAddress: 192.168.30.51
        netmask: 255.255.255.240
        useForDefaultRoute: true
    org: my-org
    vdc: my-vdc

---

