apiVersion: library.vcd.upbound.io/v1alpha1
kind: Certificate
metadata:
  annotations:
    meta.upbound.io/example-id: library/v1alpha1/certificate
  labels:
    testing.upbound.io/example-name: new-certificate
  name: new-certificate
spec:
  forProvider:
    certificate: ${file("/home/user/cert.pem")}
    description: my description
    org: myOrg
    privateKeyPassphraseSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    privateKeySecretRef:
      key: attribute.key.pem
      name: example-secret
      namespace: upbound-system

---

