/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ExternalNetworkV2IPScopeObservation struct {
}

type ExternalNetworkV2IPScopeParameters struct {

	// A FQDN for the virtual machines on this network. Only valid for NSX-V networks.
	// DNS suffix
	// +kubebuilder:validation:Optional
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// Primary DNS server. Only valid for NSX-V networks.
	// Primary DNS server
	// +kubebuilder:validation:Optional
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server. Only valid for NSX-V networks.
	// Secondary DNS server
	// +kubebuilder:validation:Optional
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Default is true.
	// If subnet is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Gateway of the network.
	// Gateway of the network
	// +kubebuilder:validation:Required
	Gateway *string `json:"gateway" tf:"gateway,omitempty"`

	// Network prefix.
	// Network mask
	// +kubebuilder:validation:Required
	PrefixLength *float64 `json:"prefixLength" tf:"prefix_length,omitempty"`

	// IP ranges used for static pool allocation in the network.  See IP Pool below for details.
	// IP ranges used for static pool allocation in the network
	// +kubebuilder:validation:Optional
	StaticIPPool []IPScopeStaticIPPoolParameters `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type ExternalNetworkV2Observation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type ExternalNetworkV2Parameters struct {

	// Network friendly description
	// Network description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// One or more IP scopes for the network. See IP Scope below for details.
	// A set of IP scopes for the network
	// +kubebuilder:validation:Required
	IPScope []ExternalNetworkV2IPScopeParameters `json:"ipScope" tf:"ip_scope,omitempty"`

	// NSX-T network definition. See NSX-T Network below for details.
	// Reference to NSX-T Tier-0 router or segment and manager
	// +kubebuilder:validation:Optional
	NsxtNetwork []NsxtNetworkParameters `json:"nsxtNetwork,omitempty" tf:"nsxt_network,omitempty"`

	// One or more blocks of vSphere Network..
	// A set of port groups that back this network. Each referenced DV_PORTGROUP or NETWORK must exist on a vCenter server registered with the system.
	// +kubebuilder:validation:Optional
	VsphereNetwork []ExternalNetworkV2VsphereNetworkParameters `json:"vsphereNetwork,omitempty" tf:"vsphere_network,omitempty"`
}

type ExternalNetworkV2VsphereNetworkObservation struct {
}

type ExternalNetworkV2VsphereNetworkParameters struct {

	// vSphere portgroup ID. Can be looked up using  vcd_portgroup data source.
	// The name of the port group
	// +kubebuilder:validation:Required
	PortgroupID *string `json:"portgroupId" tf:"portgroup_id,omitempty"`

	// vCenter ID. Can be looked up using vcd_vcenter data source.
	// The vCenter server name
	// +kubebuilder:validation:Required
	VcenterID *string `json:"vcenterId" tf:"vcenter_id,omitempty"`
}

type IPScopeStaticIPPoolObservation struct {
}

type IPScopeStaticIPPoolParameters struct {

	// End address of the IP range
	// End address of the IP range
	// +kubebuilder:validation:Required
	EndAddress *string `json:"endAddress" tf:"end_address,omitempty"`

	// Start address of the IP range
	// Start address of the IP range
	// +kubebuilder:validation:Required
	StartAddress *string `json:"startAddress" tf:"start_address,omitempty"`
}

type NsxtNetworkObservation struct {
}

type NsxtNetworkParameters struct {

	// NSX-T manager ID. Can be looked up using vcd_nsxt_manager data source.
	// ID of NSX-T manager
	// +kubebuilder:validation:Required
	NsxtManagerID *string `json:"nsxtManagerId" tf:"nsxt_manager_id,omitempty"`

	// Existing NSX-T segment name.
	// Name of NSX-T segment (for NSX-T segment backed external network)
	// +kubebuilder:validation:Optional
	NsxtSegmentName *string `json:"nsxtSegmentName,omitempty" tf:"nsxt_segment_name,omitempty"`

	// NSX-T Tier-0 router ID. Can be looked up using
	// vcd_nsxt_tier0_router data source.
	// ID of NSX-T Tier-0 router (for T0 gateway backed external network)
	// +kubebuilder:validation:Optional
	NsxtTier0RouterID *string `json:"nsxtTier0RouterId,omitempty" tf:"nsxt_tier0_router_id,omitempty"`
}

// ExternalNetworkV2Spec defines the desired state of ExternalNetworkV2
type ExternalNetworkV2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExternalNetworkV2Parameters `json:"forProvider"`
}

// ExternalNetworkV2Status defines the observed state of ExternalNetworkV2.
type ExternalNetworkV2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExternalNetworkV2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ExternalNetworkV2 is the Schema for the ExternalNetworkV2s API. Provides a VMware Cloud Director External Network resource (version 2). New version of this resource uses new VCD API and is capable of creating NSX-T backed external networks as well as port group backed ones.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type ExternalNetworkV2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ExternalNetworkV2Spec   `json:"spec"`
	Status            ExternalNetworkV2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExternalNetworkV2List contains a list of ExternalNetworkV2s
type ExternalNetworkV2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalNetworkV2 `json:"items"`
}

// Repository type metadata.
var (
	ExternalNetworkV2_Kind             = "ExternalNetworkV2"
	ExternalNetworkV2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExternalNetworkV2_Kind}.String()
	ExternalNetworkV2_KindAPIVersion   = ExternalNetworkV2_Kind + "." + CRDGroupVersion.String()
	ExternalNetworkV2_GroupVersionKind = CRDGroupVersion.WithKind(ExternalNetworkV2_Kind)
)

func init() {
	SchemeBuilder.Register(&ExternalNetworkV2{}, &ExternalNetworkV2List{})
}
