apiVersion: catalog.vcd.upbound.io/v1beta1
kind: Catalog
metadata:
  annotations:
    meta.upbound.io/example-id: catalog/v1beta1/catalog
  labels:
    testing.upbound.io/example-name: myNewCatalog
  name: mynewcatalog
spec:
  forProvider:
    deleteForce: "true"
    deleteRecursive: "true"
    description: catalog for files
    name: my-catalog
    org: my-org

---

