apiVersion: vapp.vcd.upbound.io/v1beta1
kind: IndependentDisk
metadata:
  annotations:
    meta.upbound.io/example-id: vapp/v1beta1/independentdisk
  labels:
    testing.upbound.io/example-name: myNewIndependentDisk
  name: mynewindependentdisk
spec:
  forProvider:
    busSubType: VirtualSCSI
    busType: SCSI
    sizeInMb: "1024"
    storageProfile: external
    vdc: my-vcd

---

apiVersion: vapp.vcd.upbound.io/v1beta1
kind: VM
metadata:
  annotations:
    meta.upbound.io/example-id: vapp/v1beta1/independentdisk
  labels:
    testing.upbound.io/example-name: web2
  name: web2
spec:
  forProvider:
    disk:
    - busNumber: 1
      name: logDisk
      unitNumber: 0
    vappNameSelector:
      matchLabels:
        testing.upbound.io/example-name: web

---

